# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: files.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\x12\x0b\x66ileservice\"2\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"-\n\x0eUploadResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"@\n\x10\x44ownloadResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t2\x99\x01\n\x0b\x46ileService\x12\x41\n\x06Upload\x12\x1a.fileservice.UploadRequest\x1a\x1b.fileservice.UploadResponse\x12G\n\x08\x44ownload\x12\x1c.fileservice.DownloadRequest\x1a\x1d.fileservice.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=28
  _globals['_UPLOADREQUEST']._serialized_end=78
  _globals['_UPLOADRESPONSE']._serialized_start=80
  _globals['_UPLOADRESPONSE']._serialized_end=125
  _globals['_DOWNLOADREQUEST']._serialized_start=127
  _globals['_DOWNLOADREQUEST']._serialized_end=162
  _globals['_DOWNLOADRESPONSE']._serialized_start=164
  _globals['_DOWNLOADRESPONSE']._serialized_end=228
  _globals['_FILESERVICE']._serialized_start=231
  _globals['_FILESERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
