version: "3.8"

services:
  directory-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/microservices/directory-service/index.js", "--config", "./config/directory-server.json"]
    ports:
      - "4000:4000"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files

  peer1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer1.json"]
    ports:
      - "3001:3001"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server

  peer2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer2.json"]
    ports:
      - "3002:3002"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server

  peer3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer3.json"]
    ports:
      - "3003:3003"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server
