

services:
  directory-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/microservices/directory-service/index.js", "--config", "./config/directory-server.json"]
    ports:
      - "9000:9000"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files

  peer1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer1.json"]
    ports:
      - "9001:9001"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server

  peer2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer2.json"]
    ports:
      - "9003:9003"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server

  peer3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["node", "src/server/p-servidor.js", "--config", "./config/peer3.json"]
    ports:
      - "9005:9005"
    volumes:
      - ../config:/app/config
      - ../shared-files:/app/shared-files
    depends_on:
      - directory-server
